name: Tests

on: [push]

jobs:
  build:
    name: Running tests.

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      # Python needs to be setup before checkout to prevent files from being
      # left in the source tree. See setup-python/issues/106.
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2

    - name: Installing platform dependencies
      if: matrix.os == 'ubuntu-latest'
      run: >
        sudo apt-get install -y
        build-essential
        clang-6.0

    - name: Installing python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[test]'

    - name: Running tests
      run: |
        pytest
